"""add votes automatically

Revision ID: 9570a59f8235
Revises: 6a206db2f982
Create Date: 2024-02-12 13:40:04.743522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

#alembic revision --autogenerate -m "x" -- write in terminal to import tables from models(possible due to the imports we added in env.py)


# revision identifiers, used by Alembic.
revision: str = '9570a59f8235'
down_revision: Union[str, None] = '6a206db2f982'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    # ### end Alembic commands ###
